# Iris Data Exploration using  `pandas`

## 1. Load the data

### 1-1. Without `pandas`

In [1]:
# without pandas
with open('./data/Iris.csv', 'r') as f:
    for i in range(10):
        print(f.readline().strip())

SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
5.1,3.5,1.4,0.2,Iris-setosa
4.9,3,1.4,0.2,Iris-setosa
4.7,3.2,1.3,0.2,Iris-setosa
4.6,3.1,1.5,0.2,Iris-setosa
5,3.6,1.4,0.2,Iris-setosa
5.4,3.9,1.7,0.4,Iris-setosa
4.6,3.4,1.4,0.3,Iris-setosa
5,3.4,1.5,0.2,Iris-setosa
4.4,2.9,1.4,0.2,Iris-setosa

### 1-2. With `pandas`

In [2]:
# with pandas
import pandas as pd

df = pd.read_csv('./data/Iris.csv')
df.head() # check if the dataframe is loaded properly

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            5.0           3.6            1.4           0.2  Iris-setosa

## 2. How to access to a DataFrame?

In [3]:
# shape of dataframe
df.shape

(150, 5)

In [4]:
# length of dataframe
len(df)

150

In [5]:
# check column names
df.columns

Index(['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

In [6]:
# check row indices
df.index

RangeIndex(start=0, stop=150, step=1)

In [7]:
# access a column (=series)
df['SepalLengthCm']

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ...
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: SepalLengthCm, Length: 150, dtype: float64

In [8]:
# access to a row
df.loc[2] # or, df.iloc[2]

SepalLengthCm            4.7
SepalWidthCm             3.2
PetalLengthCm            1.3
PetalWidthCm             0.2
Species          Iris-setosa
Name: 2, dtype: object

In [9]:
# Access to a Specific Value
df.loc[2, 'Species'] # or, df.iloc[2, -1]

'Iris-setosa'

## 3. Summary statistics

### 3-1. Categorical Columns

In [10]:
# See all unique categories
df['Species'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [11]:
# Count how many times each unique value appears
df['Species'].value_counts()

Species
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

### 3-2. Numerical Columns

In [12]:
# how to check the mean or the stdev of a column?
print(df['SepalLengthCm'].mean())
print(df['SepalLengthCm'].std())

5.843333333333334
0.8280661279778629

In [13]:
print(f"The mean of SepalLengthCm is {df['SepalLengthCm'].mean():.2f}")
print(f"The standard deviation of SepalLengthCm is {df['SepalLengthCm'].std():.2f}")
print(f"The median of SepalLengthCm is {df['SepalLengthCm'].median():.2f}")

The mean of SepalLengthCm is 5.84
The standard deviation of SepalLengthCm is 0.83
The median of SepalLengthCm is 5.80

In [14]:
# (advanced) check the mean of four numeric columns
for col in df.columns[:-1]:
    print(f"The mean of {col} is {df[col].mean():.2f}")

The mean of SepalLengthCm is 5.84
The mean of SepalWidthCm is 3.05
The mean of PetalLengthCm is 3.76
The mean of PetalWidthCm is 1.20

### 3-3. Get summary statistics per category

In [15]:
df.groupby('Species').mean()

                 SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
Species
Iris-setosa              5.006         3.418          1.464         0.244
Iris-versicolor          5.936         2.770          4.260         1.326
Iris-virginica           6.588         2.974          5.552         2.026

### 3-4. Summary statistics table

In [16]:
# Summary Statistics
df.describe(include='all')

        SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
count      150.000000    150.000000     150.000000    150.000000          150
unique            NaN           NaN            NaN           NaN            3
top               NaN           NaN            NaN           NaN  Iris-setosa
freq              NaN           NaN            NaN           NaN           50
mean         5.843333      3.054000       3.758667      1.198667          NaN
std          0.828066      0.433594       1.764420      0.763161          NaN
min          4.300000      2.000000       1.000000      0.100000          NaN
25%          5.100000      2.800000       1.600000      0.300000          NaN
50%          5.800000      3.000000       4.350000      1.300000          NaN
75%          6.400000      3.300000       5.100000      1.800000          NaN
max          7.900000      4.400000       6.900000      2.500000          NaN

# 4. Data Transformation

### 4.1 Filter Rows

In [17]:
# Filter Rows based on column values
filtered_df = df[df['PetalLengthCm'] > 6.0]
filtered_df

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
105            7.6           3.0            6.6           2.1  Iris-virginica
107            7.3           2.9            6.3           1.8  Iris-virginica
109            7.2           3.6            6.1           2.5  Iris-virginica
117            7.7           3.8            6.7           2.2  Iris-virginica
118            7.7           2.6            6.9           2.3  Iris-virginica
122            7.7           2.8            6.7           2.0  Iris-virginica
130            7.4           2.8            6.1           1.9  Iris-virginica
131            7.9           3.8            6.4           2.0  Iris-virginica
135            7.7           3.0            6.1           2.3  Iris-virginica

### 4.2 Add New Columns

In [18]:
# Add New Columns
df['PetalArea'] = df['PetalLengthCm'] * df['PetalWidthCm']
df['Id'] = df.index
df['Source'] = 'UCI Repository'

### 4.3. Remove Columns

In [19]:
# Remove single column
df = df.drop('Id', axis=1) # you must re-assign the variable to remove the column from the original df
# del df['Id'] # is equivalent to the line above

# remove multiple columns
df = df.drop(['PetalArea', 'Source'], axis=1) #

### 4.4 Apply a custom function using `apply()`

In [20]:
# apply a function on a single column
def shorten_species(x):
    return x.split('-')[1] # 'Iris-setosa' splits into ['Iris', 'setosa']

df['ShortSpecies'] = df['Species'].apply(shorten_species)

df[['Species', 'ShortSpecies']].head()

       Species ShortSpecies
0  Iris-setosa       setosa
1  Iris-setosa       setosa
2  Iris-setosa       setosa
3  Iris-setosa       setosa
4  Iris-setosa       setosa

In [21]:
# apply with lambda on a single column
df['PetalSize'] = df['PetalLengthCm'].apply(
    lambda length: 'short' if length < 3.0 else 'long')

df[['PetalLengthCm', 'PetalSize']].head()

   PetalLengthCm PetalSize
0            1.4     short
1            1.4     short
2            1.3     short
3            1.5     short
4            1.4     short

In [22]:
# apply a custom function on a dataframe
def calculate_petal_ratio(x): # x is a row in a dataframe
    ratio = x['PetalLengthCm'] / x['PetalWidthCm']
    return ratio

# the function is applied to every row (axis=1)
df['PetalRatio'] = df.apply(calculate_petal_ratio, axis=1)

# the above is equivalent to the below
# df['PetalRatio'] = df.apply(
#     lambda row: row['PetalLengthCm'] / row['PetalWidthCm'], 
#     axis=1)

df[['PetalLengthCm', 'PetalWidthCm', 'PetalRatio']].head()

   PetalLengthCm  PetalWidthCm  PetalRatio
0            1.4           0.2         7.0
1            1.4           0.2         7.0
2            1.3           0.2         6.5
3            1.5           0.2         7.5
4            1.4           0.2         7.0

# 5. Save the pandas dataframe to a csv file

In [23]:
df.head()

,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species,ShortSpecies,PetalSize,PetalRatio
0,5.1,3.5,1.4,0.2,Iris-setosa,setosa,short,7.0
1,4.9,3.0,1.4,0.2,Iris-setosa,setosa,short,7.0
2,4.7,3.2,1.3,0.2,Iris-setosa,setosa,short,6.5
3,4.6,3.1,1.5,0.2,Iris-setosa,setosa,short,7.5
4,5.0,3.6,1.4,0.2,Iris-setosa,setosa,short,7.0

In [24]:
df.to_csv('./iris_with_new_cols.csv', index=False)